// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalmonCookiesAPI.Data;

#nullable disable

namespace SalmonCookiesAPI.Migrations
{
    [DbContext(typeof(CookieStandDBContext))]
    partial class CookieStandDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalmonCookiesAPI.Models.CookieStand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageCookiesPerSale")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximumCustomersPerHour")
                        .HasColumnType("int");

                    b.Property<int>("MinimumCustomersPerHour")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CookieStands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageCookiesPerSale = 2.5,
                            Description = "description1",
                            Location = "Amman",
                            MaximumCustomersPerHour = 7,
                            MinimumCustomersPerHour = 3,
                            Owner = "Person1"
                        },
                        new
                        {
                            Id = 2,
                            AverageCookiesPerSale = 2.5,
                            Description = "description2",
                            Location = "Irbid",
                            MaximumCustomersPerHour = 7,
                            MinimumCustomersPerHour = 3,
                            Owner = "Person2"
                        });
                });

            modelBuilder.Entity("SalmonCookiesAPI.Models.HourlySale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StandCookieId")
                        .HasColumnType("int");

                    b.Property<int>("cookieStandId")
                        .HasColumnType("int");

                    b.Property<int>("salesvalue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("cookieStandId");

                    b.ToTable("hourlySale");
                });

            modelBuilder.Entity("SalmonCookiesAPI.Models.HourlySale", b =>
                {
                    b.HasOne("SalmonCookiesAPI.Models.CookieStand", "cookieStand")
                        .WithMany("hourlySale")
                        .HasForeignKey("cookieStandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cookieStand");
                });

            modelBuilder.Entity("SalmonCookiesAPI.Models.CookieStand", b =>
                {
                    b.Navigation("hourlySale");
                });
#pragma warning restore 612, 618
        }
    }
}
